version: "3"

services:
  brouter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:17777"
    container_name: brouter
    networks:
      - izzistrit_back_app-network

networks:
  izzistrit_back_app-network:
    external: true
